### ISSUE TITLE
High resolution icons

### ISSUE THREAD

**Issue by mystygage** [tomcatplugin/tomcatplugin#10]
The icons for the toolbar are very pixelated, especially when you are working with a dark theme.
<img width="175" alt="screenshot 2019-02-18 at 14 13 36" src="https://user-images.githubusercontent.com/1107406/52953320-6cc59380-3387-11e9-939f-10a24d714345.png">

**Comment by ConiKost** [comment]
@markuskeunecke Maura created some nice svg icons for us, which we could use here.

**Comment by markuskeunecke** [comment]
@ConiKost I'd be happy to use them if Maura provides them under a proper licence ideally including a kind of "source code" of those images.

**Comment by ConiKost** [comment]
@markuskeunecke Do you need a special license?

**Comment by markuskeunecke** [comment]
I am not sure but maybe a CC style licence would be ok

**Comment by ConiKost** [comment]
Allright, I've spoken internal with our law team. We have the permission to put the Icons under a free license. I suggest MIT here, since it's the same license, as currently the plugin itself is.

I can fill a PR for the new icons. I don't have any source code itself, as the icons were created externally for us, but we are permitted to re license here.

**Comment by markuskeunecke** [comment]
Please do so, @ConiKost. :) Thank you for your efforts!
