### ISSUE TITLE
Not clear what you mean by "path of your Tomcat installation" 

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [tomcatplugin/tomcatplugin#12]
It is not clear what you mean by "path of your Tomcat installation" -- is that the binary? the URL?

I installed tomcat 9 using homebrew on macOS. I have two ways of starting tomcat. At startup after running:
```    brew services start tomcat```
Or:
```    catalina run```

Or do you mean where the server.xml file should be located?
How do I specify my .war file?
Unfortunately the dialog isn't helping.
![screenshot](https://user-images.githubusercontent.com/40045831/54647016-3babb200-4a5e-11e9-97de-387769bd26e9.png)

**Comment by mystygage** [comment]
If you installed Tomcat with homebrew, the path to your binaries is `/usr/local/opt/tomcat/libexec`:
![image](https://user-images.githubusercontent.com/1107406/56144535-d71f3c80-5fa2-11e9-8782-f069003a0925.png)

If you use this plugin, you should start the Tomcat via the button in the bar instead of the shell scripts.
